name: forrocwb.api

services:
  api:
    image: nandoburgos/forrocwb.api
    container_name: forrocwb.api
    environment:
      - PORT=4545
      - DATABASE_URL=mysql://boz:Ewhblt69%21%40%23@boz.app.br:3306/forrocwb
      - URL=https://api-forrocwb.nandoburgos.dev
      - JWT_SECRET=0IGSGJ0IWOsdljfo
    ports:
      - "4545:4545"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

volumes:
  static_volume:
    name: "forrocwb_static_files"